version: '3.8'

services:

  backend:
    build: ./backend
    container_name: utsavnex-backend
    restart: unless-stopped

    ports:
      - "8001:8001"

    environment:
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CORS_ORIGINS=*

  frontend:
    build: ./frontend
    container_name: utsavnex-frontend
    restart: unless-stopped

    ports:
      - "3000:80"

    depends_on:
      - backend
